# Быстрая конфигурация Alertmanager для SEED v6
# Скопируйте в /etc/alertmanager/alertmanager.yml

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@company.com'

# Основная маршрутизация - все алерты идут в SEED
route:
  group_by: ['alertname', 'instance']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'seed-main'
  
  routes:
    # Критические алерты - быстро
    - match:
        severity: critical
      receiver: 'seed-critical'
      group_wait: 0s
      group_interval: 30s
      repeat_interval: 5m

receivers:
  # Основной канал SEED
  - name: 'seed-main'
    webhook_configs:
    - url: 'http://p-dba-seed-adv-msk01:8080/alertmanager'
      send_resolved: true
      
  # Критические алерты  
  - name: 'seed-critical'
    webhook_configs:
    - url: 'http://p-dba-seed-adv-msk01:8080/alertmanager'
      send_resolved: true