# =============================================================================
# Docker Compose Override - Development Configuration
# =============================================================================
# This file provides development-specific overrides
# Use: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

version: '3.8'

services:
  # Development overrides for SEED Agent
  seed-agent:
    # Enable debug mode
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      
    # Mount source code for development
    volumes:
      - ./seed.yaml:/app/seed.yaml:ro
      - ./plugins.py:/app/plugins.py:ro
      - ./logs:/app/logs
      - ./seed-agent.py:/app/seed-agent.py:ro  # Mount main binary for hot reload
      - ./core:/app/core:ro                     # Mount core modules
      
    # Override command for development
    command: ["python", "seed-agent.py", "--mode", "both", "--host", "0.0.0.0", "--port", "8080"]
    
    # Remove resource limits for development
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  # Development RabbitMQ - expose all ports
  rabbitmq:
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
      - "25672:25672"   # Clustering
      
  # Development Redis - enable Redis CLI access
  redis:
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --protected-mode no
    
    ports:
      - "6379:6379"