services:
  redis:
    image: redis:7.2-alpine
    container_name: seed-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: '0.5'

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: seed-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    ports:
      - "5672:5672"     # AMQP для SEED Agent
      - "15672:15672"   # RabbitMQ Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: '1.0'

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/redis
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/rabbitmq