# =============================================================================
# SEED Agent - Offline Configuration (без внешних образов)
# =============================================================================
services:
  # =============================================================================
  # SEED Agent - Main monitoring service (только локальная сборка)
  # =============================================================================
  seed-agent:
    # Вместо сборки используем Python образ хоста или standalone режим
    image: python:3.11-slim  # Уберите эту строку если хотите без образов
    container_name: seed-agent-offline
    restart: unless-stopped
    working_dir: /app
    command: ["python", "seed-agent.py", "--mode", "both", "--host", "0.0.0.0", "--port", "8080"]
    
    # Port mapping
    ports:
      - "8080:8080"
      
    # Environment variables
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://localhost:6379/0
      - RABBITMQ_URL=amqp://guest:guest@localhost:5672//
      
    # Volume mounts - external config and plugins
    volumes:
      - ./seed.yaml:/app/seed.yaml:ro           # Configuration file
      - ./plugins.py:/app/plugins.py:ro         # Plugins file
      - ./logs:/app/logs                        # Logs directory
      
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
          
    # Networks
    networks:
      - seed-network

# =============================================================================
# Networks
# =============================================================================
networks:
  seed-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16