hosts:
  # можно задать индивидуальный telegraf_url
  centos-s-1vcpu-512mb-10gb-fra1-01:
    telegraf_url: "http://centos-s-1vcpu-512mb-10gb-fra1-01:9216/metrics"
  
  d-dba-mng-adv-msk02:
    telegraf_url: "http://d-dba-mng-adv-msk02:9216/metrics"

# группировки если захотите в будущем
groups: {}
